# Generated by Django 4.0.4 on 2022-05-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('timeid', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('booked', models.IntegerField(blank=True, null=True)),
                ('maxnum', models.IntegerField(blank=True, null=True)),
                ('bookstate', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('inspectorid', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('inspectorpw', models.CharField(blank=True, max_length=8)),
            ],
            options={
                'db_table': 'inspector',
            },
        ),
        migrations.CreateModel(
            name='Lake',
            fields=[
                ('lakeid', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('lakename', models.CharField(blank=True, max_length=20, null=True)),
                ('lakesize', models.IntegerField(blank=True, null=True)),
                ('lakeloc', models.CharField(blank=True, max_length=20, null=True)),
                ('waterlevel', models.IntegerField(blank=True, null=True)),
                ('gatestate', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lake',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('mid', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('mpw', models.CharField(max_length=8)),
                ('mname', models.CharField(max_length=20)),
                ('msex', models.BooleanField(null=True)),
                ('mage', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'manager',
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('parkingid', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('havenum', models.IntegerField(blank=True, null=True)),
                ('maxnum', models.IntegerField(blank=True, null=True)),
                ('parkingloc', models.CharField(blank=True, max_length=20, null=True)),
                ('parkingstate', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parking',
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('roadid', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('roadlength', models.IntegerField(blank=True, null=True)),
                ('roadname', models.CharField(blank=True, max_length=20, null=True)),
                ('potholesnum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'road',
            },
        ),
        migrations.CreateModel(
            name='Toilet',
            fields=[
                ('toiletid', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('peoplenum', models.IntegerField(blank=True, null=True)),
                ('toiletloc', models.CharField(blank=True, max_length=20, null=True)),
                ('toiletclean', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'toilet',
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('treeid', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('treespe', models.CharField(blank=True, max_length=20, null=True)),
                ('treeloc', models.CharField(blank=True, max_length=20, null=True)),
                ('insectbugs', models.BooleanField(blank=True, null=True)),
                ('treewater', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tree',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('vtel', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('vname', models.CharField(max_length=10)),
                ('vtime', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'visitor',
            },
        ),
    ]
